"""merge scheduled activities into dated calendar activities

Revision ID: 18bd10881361
Revises: 5b40be6f7588
Create Date: 2026-08-13 13:51:44.531439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18bd10881361'
down_revision: Union[str, Sequence[str], None] = '5b40be6f7588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_activities')
    # Dropping the table doesn't drop the Postgres enum type it used --
    # remove it explicitly or it's left orphaned in the schema.
    sa.Enum(name='dayofweek').drop(op.get_bind(), checkfirst=True)
    op.add_column('calendar_activities', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('calendar_activities', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_activities', 'duration_minutes')
    op.drop_column('calendar_activities', 'start_time')
    sa.Enum('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', name='dayofweek').create(
        op.get_bind(), checkfirst=True
    )
    op.create_table('scheduled_activities',
    sa.Column('layer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', postgresql.ENUM('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', name='dayofweek'), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('equipment_checked', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('scheduled_activities_activity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('scheduled_activities_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['layer_id'], ['layers.id'], name=op.f('scheduled_activities_layer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('scheduled_activities_pkey'))
    )
    # ### end Alembic commands ###
