"""layer schedule profile for AI scheduling agent

Revision ID: 195a7ea8def4
Revises: 07906291c867
Create Date: 2026-08-18 12:26:19.965710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195a7ea8def4'
down_revision: Union[str, Sequence[str], None] = '07906291c867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layer_schedule_profiles',
    sa.Column('layer_id', sa.UUID(), nullable=False),
    sa.Column('meeting_days', sa.String(), nullable=False),
    sa.Column('group_character', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('layer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layer_schedule_profiles')
    # ### end Alembic commands ###
