"""add equipment_checked to calendar activities

Revision ID: 5e383c93e5b1
Revises: 6102c46096dc
Create Date: 2026-08-12 17:36:39.956968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e383c93e5b1'
down_revision: Union[str, Sequence[str], None] = '6102c46096dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'calendar_activities',
        sa.Column('equipment_checked', sa.ARRAY(sa.String()), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_activities', 'equipment_checked')
    # ### end Alembic commands ###
