"""replace activity messages with comment replies and notifications

Revision ID: 7feaa2034c9a
Revises: ffcd21fd30cc
Create Date: 2026-08-16 13:44:18.627800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7feaa2034c9a'
down_revision: Union[str, Sequence[str], None] = 'ffcd21fd30cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_messages')
    op.add_column('activity_comments', sa.Column('reply_to_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'activity_comments', 'activity_comments', ['reply_to_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('activity_comments_last_read_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activity_comments_last_read_at')
    op.drop_constraint(None, 'activity_comments', type_='foreignkey')
    op.drop_column('activity_comments', 'reply_to_id')
    op.create_table('activity_messages',
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('activity_messages_activity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('activity_messages_recipient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('activity_messages_sender_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('activity_messages_pkey'))
    )
    # ### end Alembic commands ###
