"""grade range, contact phone, boys and girls evening categories

Revision ID: 8e95b93f6953
Revises: f7bf1ab98fe5
Create Date: 2026-08-01 19:00:27.897537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e95b93f6953'
down_revision: Union[str, Sequence[str], None] = 'f7bf1ab98fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('grade_min', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('grade_max', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('contact_phone', sa.String(), nullable=True))
    op.drop_column('activities', 'age_max')
    op.drop_column('activities', 'age_min')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('age_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('age_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('activities', 'contact_phone')
    op.drop_column('activities', 'grade_max')
    op.drop_column('activities', 'grade_min')
    # ### end Alembic commands ###
