"""activity equipment list and categories

Revision ID: a5c94ce47e7a
Revises: 4f04784cf1e1
Create Date: 2026-08-01 18:29:47.984338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c94ce47e7a'
down_revision: Union[str, Sequence[str], None] = '4f04784cf1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'activities',
        sa.Column('equipment', sa.ARRAY(sa.String()), nullable=False, server_default='{}'),
    )
    op.add_column(
        'activities',
        sa.Column('categories', sa.ARRAY(sa.String()), nullable=False, server_default='{}'),
    )
    op.alter_column('activities', 'equipment', server_default=None)
    op.alter_column('activities', 'categories', server_default=None)
    op.drop_column('activities', 'required_equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('required_equipment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('activities', 'categories')
    op.drop_column('activities', 'equipment')
    # ### end Alembic commands ###
