"""user institution_id/role nullable, layer join_code

Revision ID: b053f57b4c2b
Revises: 0d5591f50962
Create Date: 2026-07-31 15:16:59.374743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b053f57b4c2b'
down_revision: Union[str, Sequence[str], None] = '0d5591f50962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('join_code', sa.String(length=8), nullable=False))
    op.create_unique_constraint(None, 'layers', ['join_code'])
    op.alter_column('users', 'institution_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('institution_admin', 'counselor', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('institution_admin', 'counselor', name='userrole'),
               nullable=False)
    op.alter_column('users', 'institution_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'layers', type_='unique')
    op.drop_column('layers', 'join_code')
    # ### end Alembic commands ###
