"""unique constraint on institution name

Revision ID: b5f7ec1d7539
Revises: b053f57b4c2b
Create Date: 2026-08-01 13:22:55.728177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f7ec1d7539'
down_revision: Union[str, Sequence[str], None] = 'b053f57b4c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'institutions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'institutions', type_='unique')
    # ### end Alembic commands ###
